[PATCH] Creation of botmanager unit tests
Global-Financial-Automation/TradingBot pull request #96
Opened 2023-03-23 01:30 UTC by yamf0

- botmanager new and exit message handler test
- botmanager openmessage handler test
- userManager DB utils test

2023-03-23 04:53 UTC, hugozepeda18 requested changes

2023-03-23 04:53 UTC, hugozepeda18 commented on tradingBot/src/mktStrategy/entryStrategies/bands.py
> +        enterShort = False
por que esto esta activo?

2023-03-23 04:53 UTC, hugozepeda18 commented on tradingBot/src/mktStrategy/entryStrategies/cross.py
> +        enterShort = not enterLong
igual que arriba

2023-03-23 21:08 UTC, yamf0 commented on tradingBot/src/mktStrategy/entryStrategies/bands.py
> +        enterShort = False
Done

2023-03-23 21:08 UTC, yamf0 commented on tradingBot/src/mktStrategy/entryStrategies/cross.py
> +        enterShort = not enterLong
done

2023-03-25 04:45 UTC, hugozepeda18 approved these changes
LGTM

2023-04-18 03:39 UTC, merged